-- Türkçe locale. Editable — NOT encrypted by escrow.
Locales = Locales or {}

Locales['tr'] = {
    chat = {
        noPermission = "Yetkiniz yok.",
    },

    ui = {
        header = { subtitle = "Dinamik Hava", close = "Kapat" },

        panel = {
            areas = "Alanlar",
            backToZones = "Bölgeler Menüsüne Dön",
            backToCities = "Şehirler Menüsüne Dön",
            upNext = "Sıradaki",
            dynamic = "Dinamik",
            static = "Statik",
            noForecast = "Henüz planlanmış hava yok.",
            addWeather = "Yeni Hava Ekle",
            enableHint = "Tahmin çizelgesini düzenlemek için dinamik havayı etkinleştir.",
            changeStatic = "Statik Havayı Değiştir",
            changeStaticAll = "Tümü İçin Statik Havayı Değiştir",
            enableDynamic = "Dinamik Havayı Aç",
            disableDynamic = "Dinamik Havayı Kapat",
            noZones = "Henüz çizilmiş bölge yok.",
            reorder = "Sırala",
            wide = "Geneli",
            confirm = "Onayla",
        },

        map = {
            zoneEditor = "Bölge Düzenleyici",
            forecast = "Tahmin",
            draw = "Çiz",
            reset = "Sıfırla",
            confirm = "Onayla",
            drawHint = "Bölge için Draw'a tıkla.",
            overlap = "Bölgeler üst üste gelemez — şekli düzenleyip tekrar deneyin.",
            zoneBase = "Bölge Katmanı",
            cityWide = "Şehir Geneli",
            info = {
                title = "Bölge Editörü Yardım",
                draw = "Draw: haritaya tıklayarak köşe noktaları ekle.",
                box = "Box: tıkla, hazır dikdörtgen gelir — köşelerden boyutlandır, ortadan tutup taşı.",
                move = "Shape: köşe noktalarını sürükleyerek yerlerini değiştir.",
                addPoint = "Shape: bir kenara çift tıklayarak yeni köşe ekle.",
                curve = "Shape: kenar ortasındaki tutamaçtan o kenara kavis ver.",
                confirm = "Confirm ile bölgeyi oluştur.",
            },
            tools = {
                drawZone = "Bölge çiz",
                shape = "Şekil",
                box = "Kutu",
                rename = "Bölgeyi yeniden adlandır",
                hide = "Bölgeleri gizle",
                undo = "Noktayı geri al",
                redo = "Noktayı yinele",
                resetDraft = "Taslağı sıfırla",
                confirm = "Bölgeyi onayla",
                changeColor = "Rengi değiştir",
                delete = "Bölgeyi sil",
            },
        },

        modals = {
            selectType = "Hava Tipi Seç",
            temperature = "Sıcaklık",
            time = "Saat",
            addWeatherCta = "Hava Ekle",
            myZone = "Bölgem",
            centigrade = "Santigrat",
            fahrenheit = "Fahrenhayt",
            changeStaticTitle = "Statik Havayı Değiştir",
            createZoneTitle = "Hava Bölgesi Oluştur",
            createZoneCta = "Hava Bölgesi Oluştur",
            zoneNameColor = "Bölge Adı & Renk",
            currentWeather = "Mevcut Hava",
            renameTitle = "Bölgeyi Yeniden Adlandır",
            renameCta = "Kaydet",
            zoneName = "Bölge Adı",
            addTitle = "Yeni Hava Ekle",
            editTitle = "Havayı Düzenle",
            editCta = "Hava Ayarlarını Kaydet",
            timeTaken = "Bu saatte zaten bir tahmin var.",
        prevCastTime = "Önceki hava başlangıç saati {time}",
            currentlyAt = "Şu an {weather} — {time}",
            cancel = "İptal",
            confirm = "Onayla",
            deleteCta = "Sil",
            deleteZoneTitle = "Bölgeyi Sil",
            deleteZoneMessage = "Bu bölgeyi silmek istediğine emin misin? Bu işlem geri alınamaz.",
        },

        toast = {
            weatherSet = "Hava güncellendi",
            weatherAllSet = "Tüm alanlara hava uygulandı",
            dynamicOn = "Dinamik mod açıldı",
            dynamicOff = "Dinamik mod kapatıldı",
            zoneCreated = "Bölge oluşturuldu",
            zoneRenamed = "Bölge yeniden adlandırıldı",
            zoneDeleted = "Bölge silindi",
            forecastAdded = "Tahmin eklendi",
            forecastUpdated = "Tahmin güncellendi",
            forecastRemoved = "Tahmin silindi",
        },

        relative = {
            now = "Şimdi",
            inMin = "{n} Dk Sonra",
            inHour = "{n} Saat Sonra",
            inHours = "{n} Saat Sonra",
        },

        weather = {
            EXTRASUNNY = "Çok Güneşli",
            CLEAR = "Açık",
            NEUTRAL = "Nötr",
            SMOG = "Puslu",
            FOGGY = "Sisli",
            CLOUDS = "Bulutlu",
            OVERCAST = "Kapalı",
            CLEARING = "Açılıyor",
            RAIN = "Yağmurlu",
            THUNDER = "Fırtınalı",
            SNOWLIGHT = "Hafif Kar",
            SNOW = "Karlı",
            BLIZZARD = "Tipi",
            XMAS = "Yılbaşı",
            HALLOWEEN = "Cadılar Bayramı",
        },
    },
}
