CREATE TABLE IF NOT EXISTS `player_needs` (
    `identifier` VARCHAR(100) NOT NULL PRIMARY KEY,
    `poop` INT NOT NULL DEFAULT 0,
    `sleep` INT NOT NULL DEFAULT 0,
    `pee` INT NOT NULL DEFAULT 0,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
